---
# tasks file for deploy_nginx9999
  - name: Update package and install nginx
    ansible.builtin.apt:
      name: nginx
      state: present
      update_cache: yes

  - name: Copy nginx configuration file
    template:
      src: nginx.conf.j2
      dest: "{{nginx_config_file}}"
    notify: 
      - Reload nginx

  - name: Copy index.html
    ansible.builtin.template:
      src: index.html.j2
      dest: /var/www/html/index.html
    notify: 
      - Reload nginx

  
  - name: start nginx service 
    ansible.builtin.systemd_service:
      name: nginx.service
      state: started
      enabled: true
