---
  - name: Установка зависимостей
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      state: latest
    when: ansible_os_family == 'Debian'

  - name: Добавление Docker GPG ключа
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    when: ansible_os_family == 'Debian'

  - name: Добавление репозитория Docker
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    when: ansible_os_family == 'Debian'

  - name: Обновление списка пакетов
    apt:
      update_cache: yes
    when: ansible_os_family == 'Debian'

  - name: Установка Docker
    apt:
      name: docker-ce
      state: latest
    when: ansible_os_family == 'Debian'

  - name: Запуск Docker службы
    service:
      name: docker
      state: started
      enabled: yes

  - name: adding user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
