---
  - name: Create a directory
    ansible.builtin.file:
      path: /tmp/templates
      state: directory
      mode: '0644'

  - name: Copy index.html
    copy:
      src: '{{item}}'
      dest: /tmp/templates
    loop:
    - ./files/index2.html
    - ./files/nginx1.conf
    - ./files/nginx2.conf
